// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://japhrkohqnslieqeuodn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImphcGhya29ocW5zbGllcWV1b2RuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2NTAxNDcsImV4cCI6MjA3MzIyNjE0N30.ojxILnrhEnag8ShhMnC2AsqS4O-mW_VvjejOEGd0R3A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
      // Token refresh จะเกิดขึ้นอัตโนมัติเมื่อใกล้หมดอายุ
      // JWT expiry จะต้องไปตั้งจาก Supabase Dashboard -> Settings -> API
    },
  }
);
